# Generated by Django 4.2.7 on 2023-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_alter_product_image_delete_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
