name: Django CI

on:
  push:
    branches: [ "master", "tests" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 'ps_password'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Create PostgreSQL database
    #   run: |
    #     psql -c 'create database django_db owner postgres;' -U postgres

    - name: Run Magrations and Tests
      run: |
        python manage.py migrate
        python manage.py test ././shop/tests/
